### ISSUE TITLE
Suggestion: fade current song when it ends or changes

### ISSUE THREAD

**Issue by Jin-Jiyunsun** [alowaniak/music-replacer#1]
It currently is kind of jarring when a song changes as it simply cuts off instantly, I suggest making the currently played track fade when it gets changed for a new track, be that another custom one or a vanilla.

Otherwise amazing plugin,  thanks for you work!

**Comment by alowaniak** [comment]
Fading is a bit more involved than I would've hoped so I'm not sure when/if I'll have it added but I'll definitely try.
I'll also focus on only a fade-out since that's how I interpret "making the currently played track fade" and afaict that's how the osrs music behaves.
