### ISSUE TITLE
I can't get this to work anymore

### ISSUE THREAD

**Issue by NarZook** [alowaniak/music-replacer#13]
Aside from the plugin deleting the .wav file everytime I remove the override, it just doesn't to play the new music (despite giving it an identical name). Not sure if an update borked it, but it definitely don't work no more. Shame. :(

**Comment by Jorge-D-Robles** [comment]
Same here - just installed the plugin but it isn't working no matter what I tried. Some update must have broken the plugin.

**Comment by ezille** [comment]
Also happening with me. I’m so sad!!! This is my favorite plugin. It has been broken since the “random” music button. :(

**Comment by Weeabuto** [comment]
Yup, latest game update broke the plugin.

**Comment by awordley** [comment]
Hopefully the creator fixes it soon, this plugin really does change the game experience so much. I've tried adding them on Discord to message and hopefully see if they're planning on fixing it but haven't received a friend requst back yet. Here's hoping!

**Comment by alowaniak** [comment]
Sorry for the late reply everyone, a small change in music player broke it.
I've fixed it, just gotta wait until the [pull request](https://github.com/runelite/plugin-hub/pull/4549) is accepted by runelite devs.
