### ISSUE TITLE
Bulk override tracks option doesn't show in 'Resizable - Modern layout'

### ISSUE THREAD

**Issue by CypherNL** [alowaniak/music-replacer#2]
The option to bulk override tracks doesn't show in the modern layout of resizable, but does in the classic layout. The fixed layout does also show the option. So only the modern layout misses this feature.

![2022-02-16_19-35-49](https://user-images.githubusercontent.com/11279045/154333180-a07c0a8b-5376-4e15-82f3-83275acaa591.png)
![2022-02-16_19-35-57](https://user-images.githubusercontent.com/11279045/154333188-9eb5b33f-af2a-46bc-8fe0-2bfc922a6f30.png)

**Comment by alowaniak** [comment]
Much appreciate the bug-report, thanks :)
It should be fixed (on the phub when https://github.com/runelite/plugin-hub/pull/2433 is merged)!

**Comment by RerEirikr** [comment]
Just FYI: this seems to be a bug again with the current version. The GIF in the example page didn't show how to do the mass override so I was going crazy thinking I broke something. Really helpful for having this thread here though, thanks!
