### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Vaksky** [alowaniak/music-replacer#4]
Won't pull song from youtube, and won't use local file as well after today's update.

**Comment by alowaniak** [comment]
My apologies for the late reply.
I'm not entirely sure how local file couldn't have worked, are you sure you used a CD-quality .wav file?
As that's currently the only format it can play.

Pulling songs from youtube should now work again though.

**Comment by BLARGoMATIC** [comment]
.wav files dont seem to be working or pulling from youtube.

The track is bold, but the music itself isn't being replaced.

**Comment by alowaniak** [comment]
Yesterday's osrs update indeed broke it (the Widget ID for the current playing song changed).
I've committed a fix and made a [PR to the plugin-hub](https://github.com/runelite/plugin-hub/pull/3065), however the PR also contains other changes that might cause the approval to take longer.

I'll re-open the issue for now, but it should be fixed as soon as the PR is accepted.

**Comment by dginovker** [comment]
Seems to be working now, close?

**Comment by alowaniak** [comment]
Got indeed fixed a while back thanks for mentioning it.
