### ISSUE TITLE
Override From Youtube Failing

### ISSUE THREAD

**Issue by FlamingoChest** [alowaniak/music-replacer#6]
Overrides from youtube are failing.

I've tried several different songs but all keep failing. 

Also says to check logs but i cannot find the logs anywhere

**Comment by alowaniak** [comment]
Is this still happening for you? Because it was broken at least from yesterday until a few hours ago but it should work again now.

To find the logs, you can do one of the following:
- If your client failed to open, click the Open logs folder button.
- Open the screenshot directory by right-clicking 📷 Camera button, navigate 1 directory up, then open logs folder.
- Navigate to %userprofile%\.runelite\logs on Windows or $HOME/.runelite/logs on Linux and macOS.

**Comment by FlamingoChest** [comment]
</html>

	at nl.alowaniak.runelite.musicreplacer.YouTubeSearcher.getSearchResults(YouTubeSearcher.java:46)
	at nl.alowaniak.runelite.musicreplacer.YouTubeSearcher.lambda$search$0(YouTubeSearcher.java:40)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2022-09-01 22:15:08 [Client] ERROR n.r.c.p.t.farming.FarmingTracker - Offset error! Observed new offset of 25, previous observed offset was 15 (15) Player Loc:WorldPoint(x=2947, y=3368, plane=0)

this is what i found its giving an error

**Comment by alowaniak** [comment]
I think you're missing part of the error message, there should be some more above it.
(Alternatively you could just drop the whole client log file.)

**Comment by FlamingoChest** [comment]
[client_2022-09-01.0.log](https://github.com/alowaniak/music-replacer/files/9481168/client_2022-09-01.0.log)

**Comment by alowaniak** [comment]
No problem :)
This looks like it's the problem that existed up until a few hours ago (my server was down).
Are you sure you're *still* having this issue?

**Comment by FlamingoChest** [comment]
currently still having this issue. i just tried it just now and said failed

**Comment by alowaniak** [comment]
Could you perhaps also send the new client log?
And check if you can access [](https://alowan.nl/runelite-music-replacer/search/framing%20hanley) (it's what the plugin tries to access).
Only thing I can imagine that might be happening is if you're searching for the same thing and the error is cached for some reason.

**Comment by FlamingoChest** [comment]
[client.log](https://github.com/alowaniak/music-replacer/files/9481223/client.log)

**Comment by FlamingoChest** [comment]
yeah i clicked that link and its taking me to some gibberish coding line lmao

**Comment by alowaniak** [comment]
Ah seems to be something wrong when it tries to dl the audio from youtube.
I'm afraid this might take a while to get fixed (I use another library for the youtube stuff, so they have to fix it first).
So for the time being you probably won't be able to search for new songs.

(Any songs already cached on my server should work though, so the osrsbeatz and rs3 (presets) should work.)

**Comment by FlamingoChest** [comment]
yeah, they're working fine just overriding seems to be the issue. but thank you! sorry it dragged out a bit but glad i was able to help you find the error for the little bit i did lmao

**Comment by alowaniak** [comment]
I've done a work-around which works for now, I'm not entirely sure if this work-around will work in all cases though.
But AFAICT it should be fixed now, please let me know if it isn't for you.

And definitely no problem "it dragged out a bit", always happy to help and thank you for letting me know of the issue :)
